cantools/cantools

cantools/db.py
My DBC file has multiple ECU names; this properly parses them.
=> Properly parse multiple ECU names

cantools/db/formats/kcd.py, cantools/db/message.py, tests/files/the_homer.kcd, tests/test_cantools.py
Fixed by:
- Reading length attribute in kcd format.
- Shorting the returned data to specified length with python slice operator.
=> Fixes #8: Messages always encoded with 8 bytes.

cantools/db/bus.py, cantools/db/formats/kcd.py, tests/files/the_homer.kcd, tests/test_cantools.py
Adding support for:
- Document's version attribute
- Bus' baudrate attribute
- Message's interval attribute
Also correcting the default endianess to little, as told by https://github.com/dschanoeh/Kayak/blob/master/Kayak-kcd/src/main/resources/com/github/kayak/canio/kcd/loader/Definition.xsd
=> Support for missing or incorrect attributes in Kayak format

cantools/db/formats/kcd.py, cantools/db/message.py, cantools/db/signal.py, tests/files/the_homer.kcd, tests/test_cantools.py
Hello,
Kayak file format has value types "single" and "double" for IEE754 floats. This PR adds support for encoding and decoding these types.
=> Add support for float (single and double precision) in Kayak file format

cantools/db/message.py
Hi Erik,
Thank you for working on cantools! I have been using your library for just a few days now and finding it pleasant to work with. It's 3-4x faster than the CAN parser I was previously using. Good work on that. 
Note: I started using cantools by recommendation by Nick Kirkby, another Tesla engineer -- not sure if you've talked with him yet, but he's working on adopting.
Please take a look at this PR. I'm not 100% sure this is the right way to resolve for all cases -- there might be some shops who send empty muxes without enumerating mux values -- but this seemed like the least disruptive change that would suppport our needs.
See commit text below:
---
Our DBCs include messages in which, for some values of the multiplexer
signal, the multiplexer signal is the only signal included in …
=> Handle named multiplexers without signals

cantools/db/formats/dbc.py, tests/files/attributes.dbc, tests/test_database.py
Handles quoting STRINGs and ENUMs correctly now.
=> Fixed unnecessary type conversion in dump.

cantools/__init__.py, cantools/database/utils.py, tests/files/no_sender.dbc, tests/test_database.py
Vector's CANdb++ tool can create .dbc-files containing messages with no senders. The cantools dump subcommand currently chokes on such files. This change adds support for messages with no senders.
Technically, only the format_and function needs to be changed, but I also changed the format_or function for consistency and robustness.
=> Support for messages with no senders in dump subcommand.

Makefile
Currently the `Makefile` does not specify a `.PHONY` target, which causes `make` to treat the target as a file. Since the current `make` targets `{test,test_c,test-sdist,release-to-pypi}` do not create these target files, if a file of the same name exists in the repository the target will not work correctly (and will not run).
```bash
mkdir -p test
make test
```
Adding `.PHONY` specifies that the target is not a file, such that the target will run the recipe regardless of whether there is a file of the same name.
=> Add .PHONY targets to Makefile

Makefile
Add `-Wextra` flag as per discussion in #76.
There may be additional warnings not covered by `-Wall -Werror -Wextra -Wpedantic` that might also be useful to enable.
=> Enable -Wextra warnings

.travis.yml, Makefile, tests/dummy.c
This change adds GCC 8 support in Travis CI.
Let me know if there's some `Makefile` style things you want changed&mdash;the `CC` variable can probably be passed in the `.travis.yml` file, and a separate variable can be used to identify the version (if binaries are named differently) and determine which warnings to enable (which would get rid of this CI-only target).
=> Add GCC8 support in Travis CI tests

Makefile, tests/main.c
Floating point numbers should not be directly compared. Instead, they
should be compared against an epsilon value which denotes the maximum
allowed error.
=> Fix floating point comparison usage in test harness

.travis.yml, Makefile
This change enables clang builds on Travis CI.
The main reason why I think it'd be useful to also enable clang builds is:
1. Compiling with different compilers helps increase the chances of catching non-portable usage and undefined behaviour
2. Clang has a bunch of sanitizers which are very useful for development. I've enabled UBSan and ASan, which should be the most beneficial towards the goal of stamping out undefined behaviour.
3. It isn't uncommon to find projects using Clang, now that the generated code size is getting better.
I've gone through and enabled a bunch of warnings that I thought would be useful. Turns out the generated code doesn't need any additional changes for this giant list.
=> Enable clang-7 builds on Travis CI

cantools/database/can/c_source.py, tests/files/c_source/choices.c, tests/files/c_source/floating_point.c, tests/files/c_source/motohawk.c, tests/files/c_source/motohawk_no_floating_point_numbers.c, tests/files/c_source/multiplex.c, tests/files/c_source/multiplex_2.c, tests/files/c_source/my_database_name.c, tests/files/c_source/no_signals.c, tests/files/c_source/padding_bit_order.c, tests/files/c_source/signed.c, tests/files/c_source/vehicle.c
Remove `UNUSED` macro and `(void)` cast instead, fixing the Function-like macro advisory diagnostic.
Not sure if you want to take this change, since this is an advisory MISRA guideline. But I guess if people compile with flags to warn when macros are redefined and have their own `UNUSED` macro, then this could cause warnings? But IMO it shouldn't pollute the global namespace if it isn't absolutely necessary.
=> Remove UNUSED macro to silence MISRA diagnostic

cantools/database/can/environment_variable.py, cantools/database/can/formats/dbc.py, tests/files/emc32.dbc, tests/test_database.py
Implemented a new `environment_variables` _property_ inside `DbcSpecifics` _class_, which contains an ordered dictionary of all environment variables.
=> DBC parsing: add support for Environment Variables

cantools/tester.py, examples/motor_tester/main.py, examples/motor_tester/motor.py, setup.py
The `socketcan_native` and `socketcan_ctypes` interfaces have been
deprecated in `python-can` as of `Version 2.2.0 (2018-06-30)`, and are
superseded by the `socketcan` interface. All the examples have been
updated to updated to use the `socketcan` interface instead.
**Note**: As of `2.2.0`, `python-can` dropped support for Python 3.3, so with
the update in `setup.py`, this implicitly drops support for that as well.
=> Fix deprecation warnings for SocketCAN interfaces in examples

cantools/subparsers/monitor.py, cantools/subparsers/utils.py, tests/files/dbc/msxii_system_can.dbc, tests/test_command_line.py, tests/test_monitor.py
Totally forgot I had this patch lying around, after getting caught up
with school again. I cleaned it up, so might as well toss it up for an
initial review.
I'm not sure if this is the right general approach, but I basically
decided that it would be ideal not to modify the `Signal` and `Message`
classes, since this is purely presentation (and those are exposed).
Currently this doesn't affect filtering, which is a plus in my books.
This still displays the message name as the original name, instead of
appending the MUX identifier.
=> Separate MUX'd signals in monitor subparser output

tests/files/dbc/issue_62.dbc, tests/files/dbc/issue_63.dbc
BU_ section is mandatory. CANdb++ is not able to open a file without such section.
=> Fix test dbc files to include BU_ section

cantools/database/can/formats/dbc.py, tests/files/dbc/attributes.dbc, tests/test_tester.py
cantools.database.can.bus.py only used for .kcd parsing (need .dbc support) #127
=> Add support for Bus name and baudrate with .dbc files 

cantools/database/can/formats/dbc.py, tests/files/dbc/empty_choice.dbc, tests/test_database.py
I frequently encounter dbc-files with empty VAL_ entries. That's probably a bug in the tool generating said dbc-files, but other tools for loading and manipulating dbc-files are able to open them correctly. So cantools should too.
=> Support empty VAL_ entries in dbc-files

cantools/database/can/formats/dbc.py, tests/test_database.py
Currently the `as_dbc_string` function ignores `float` and `double` signal
attributes that identify a `Signal` as a floating type. As such, when a
DBC containing floating types is loaded and subsequently dumped, we lose
information regarding these floating-point `Signals`.
This fixes `as_dbc_string` to also dump `SIG_VALTYPE_`.
=> Add float SIG_VALTYPE_ types to DBC string dump

cantools/subparsers/monitor.py, tests/test_monitor.py
Pagination is mapped to <kbd>PgDn</kbd> (Next Page) and <kbd>PgUp</kbd> (Prev. Page),
allowing content to overflow the visible screen and still be rendered on
a new page.
=> Add support for pagination in monitor subparser

cantools/subparsers/monitor.py, cantools/subparsers/utils.py, tests/test_monitor.py
Fix a crash when the MUX index is not specified inside the DBC file. In
this case, we previously would crash with the following error:
IndexError: list index out of range
This would happen because the MUX decoding would fail and raise an error
when an invalid MUX index was passed, but the DecodeError would be
caught and then serialized into a string, leading to the IndexError
when the code later attempted to index into it.
This change propagates the error to the monitor subparser's update
function. Here, we handle the invalid MUX index the same way as if we
received an unexpected CAN message that wasn't specified in the DBC, and
discard the message.
=> Fix crash when MUX index is not specified in DBC

cantools/database/can/formats/dbc.py, tests/files/dbc/mod_name_len_dest.dbc, tests/files/dbc/mod_name_len_src.dbc, tests/test_database.py
Objects (messages, signals, nodes) with an original name >32 chars and a modified name <= 32 chars are now dumped correctly.
=> Bugfix for dumping dbc with objects whose names have been shortened

cantools/database/can/formats/dbc.py
The frame id in the SIG_VALTYPE_ value is wrong when writing the dbc as string if extended frame is valid
=> fix SIG_VALTYPE_ item on DBC dump for extended frame id messages

cantools/database/can/formats/dbc.py, cantools/database/can/signal.py, tests/files/dbc/j1939.dbc, tests/test_database.py
Added SPN attribute to signal attributes.
Added SPN support to tests. But currently tests are broken in `master`, only python-tests are passed successfully.
=> Support SPN attribute for signals

cantools/database/can/message.py, tests/test_database.py
since `value` is a `Decimal` and `signal.{minimum, maximum}` are both `float`s,
the check might fail due to floating point errors, even if `value` is
within the range but very close to / exactly `signal.{minimum, maximum}`.
Thank you for the great tools and library!
=> message: compare ranges with Decimal values

cantools/tester.py
This PR should resolve the issue #183 
I've introduced a new method which initializes the signals with their "initial values". If this is not set I am checking if 0 is in the signals valid range. If this is also not given, I am setting the value to the signals minimum value.
I am not exactly sure if the minimum value in the last case is the best solution. Please let me know if you have any other suggestions.
=> Fix out of range signal initialization (#183)

cantools/database/can/formats/dbc.py, tests/files/dbc/issue_228.dbc, tests/test_database.py
Fix for issue #228 
Added support for empty signal groups in DBC files with corresponding test
=> Empty signal groups

cantools/database/can/formats/dbc.py, tests/files/dbc/bus_comment.dbc, tests/test_database.py
Updated dbc.py to handle comment for Bus.
For comment Sequence after CM_ is choice. ex: CM_ "Special Release";
Test:
Added new file bus_comment. added funtion "test_bus_comment" in test_database to read commnet & check.
=> Fix: comment handling for database in dbc format

cantools/subparsers/monitor.py, tests/test_monitor.py
Added a cli flag to `monitor.py` exposing the `fd` boolean argument in python-can's Bus constructor. Enables use of the monitor tool with CAN FD buses, for python-can bus interfaces that support it.
=> Added support for CAN FD in monitor.py cli tool

cantools/database/can/formats/arxml.py, tests/test_database.py
This is the beginning of a series to replace https://github.com/eerimoq/cantools/pull/185. I am going to split up the improvements to small patches to ease reviewing (and will close #185). I hope, this is OK. The branch containing all the changes which I'd eventually get merged is here: https://github.com/Daimler/cantools/tree/arxml_refactor
Here comes the first (rather simple) of these patches:
Using the name of the `i-signal-to-i-pdu` mapping as the signal name seems to be conceptually wrong, so let's use the name of the `i-signal` instead. (The files I have to work with on a daily basis use garbage names for the `i-signal-to-i-pdu-mapping`s and reasonable ones for the `i-signal`s...)
Andreas Lauser <andreas.lauser@mbition.io>, Mercedes-Benz AG on behalf of [MBition …
=> ARXML: use the name of the signal as the signal name

cantools/database/can/formats/arxml.py, tests/files/arxml/system-dangling-reference-4.2.arxml, tests/test_database.py
This PR continues the quest for ARXML-3 support, cf https://github.com/Daimler/cantools/tree/arxml_refactor
In this PR a set improved of traversal functions for ARXML documents is introduced and the existing code is changed to use them. The main advantage of them is that they make it very easy to follow ARXML references and to specifies colletions of XML nodes which might have ARXML references in their location.
Be aware that I'm not sure where exactly references are allowed by the AUTOSAR standard or how to obtain that information, so I've enabled them quite liberally. The rationale is that if AUTOSAR does not allow references in a given context but we support them anyway, well-formed files will still load fine.
Andreas Lauser <andreas.lauser@mbition.io>, Mercedes-Benz AG on behalf of …
=> Introduce new ARXML traversal functions

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/files/arxml/system-illegal-namespace-4.2.arxml, tests/files/arxml/system-illegal-root-4.2.arxml, tests/files/arxml/system-illegal-version-4.2.2.1.0.arxml, tests/test_database.py
In this PR, the XML namespace handling for ARXML files is improved and a method to conveniently compare AUTOSAR versions in the code is introduced.
=> Arxml namespace improvements

cantools/database/can/formats/arxml.py, tests/test_database.py
By convention, Python prefixes methods and attributes that are not meant for public consumption by an underscore. This patch does this for the ARXML SystemLoader class.
=> ARXML SystemLoader: prefix all internal methods and attributes with an underscore

cantools/database/can/formats/arxml.py, cantools/database/can/message.py, cantools/database/can/signal.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py
ATTENTION: This patch includes some changes outside of the ARXML loader.
For now, the default is to assume that comments which don't explicitly specify a language are in English. An alternative would be to check if the dictionary containing the comments contains exactly a single element and use that instead. The problem with this approach is that comments for different languages might get mixed up more easily: Assume a supplier based in China who documents its signals only in Chinese and a OEM based in Brazil who likes to document its stuff using Portuguese... …
=> implement multi-lingual message and signal descriptions

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py
We are getting closer to the wrap up: These are small unrelated issues I've stumbled over while hacking on the ARXML parser: The first patch makes all floating point types signed (because IEEE754 types are always signed), the second patch recognizes more encodings for integers because ARXML also supports non-two complement encodings (actually decoding the CAN frames is left for another day, though) and in the last patch, I've added UUID attributes  to the `system-4.2.arxml` file to aid debugging.
[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md# …
=> Miscellaneous fixes for the ARXML code

cantools/subparsers/decode.py, tests/test_command_line.py
recognize output from e.g. `candump -tA` and `candump -tz`
=> decode: allow timestamp

cantools/subparsers/plot.py, setup.py
Regarding issue #259.
This patch makes matplotlib optional and prints a helpful message if it fails to import at runtime.
=> Make matplotlib optional

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py
This PR adds support for determining the length of a given signal via the system signal if the length is not specified by the i-signal itself (first patch),  it corrects determining the possible range of signals (second patch; the possible value range of the signal is the range over all COMPU-SCALEs, not just the first one)  and it implements loading the initial value of signals (third patch).
The next PR will contain the changes for the differences between ARXML-3 and ARXML-4.
=> ARXML: fix determining signal lengths their initial value and its range

cantools/database/can/formats/arxml.py, tests/files/arxml/system-3.2.3.arxml
Currently just the top level packages are checked. I recently stumbled over a file in the wild which needs this atrocity.
This PR is a replacement for https://github.com/eerimoq/cantools/pull/174 and it hopefully completes the refactoring of the ARXML code.
=> ARXML: Recursively check all AR-PACKAGES for CAN clusters

README.rst, setup.py
This declares the optional dependency to matplotlib.
In relation with #259, #260 and #265.
@eerimoq, I don't know what process you would like the contributors to follow when they author commit themselves. So for now I just make PR for review by other maintainers.
=> Adds "plot" extra in setup.py

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml
in essence, this means replacing `int(my_string_value)` by `int(my_string_value, 0)`. For some reason, python does not recognize numbers that start with a 0 and continue with a digit as octal, but AUTOSAR does, so this needs to be handled as a special case.
note that with this patch, python's "0o" prefix for octal numbers is also recognized. As far as I know, AUTOSAR does not allow that, but as long as we properly recognize everything which AUTOSAR specifies, I don't see a big problem with that...
=> ARXML: allow to specify non-base 10 integer numbers

cantools/__init__.py, cantools/logreader.py, cantools/subparsers/decode.py, tests/test_logreader.py
Adds a logreader module to get a common interface for parsing logs. I was really after a way to add support for CAN FD logs (which is a bonus in this one) and noticed that both decoder and plot had their own parsers.
I made an attempt to refactor plot. Didn't get my head around all the stuff that's going on in the TimestampParser and the parsing of the output from decode just seems strange to have there at all IMO. I got nice plots with timestamps and all with a lot less code in there, but many tests were still failing.
=> Add logreader module

cantools/subparsers/generate_c_source.py, tests/test_command_line.py
=> Add --output-directory option to generage_c_source command

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py
This makes it possible to specify the physical unit of a signal via its CompuMethod in addition to the PhysicalProps. In addition to this, an "ignore list" is introduced because the files which I have to deal with on a daily basis annoyingly use the pseudo unit "NoUnit" for signals which do not exhibit a physical unit.
=> ARXML: improved unit loading

cantools/__init__.py
This is a generalized solution for https://github.com/eerimoq/cantools/pull/280, and IMO it even is a bit simpler. @AxelVoitier: please leave a comment what you think about this approach.
After this, if a given subparser cannot be imported for whatever reason, the CLI still works with the remaining subparsers and an error message is printed if a non-working subparser is attempted to be invoked.
Note that this patch might slightly complicate debugging subparsers because it is slightly harder to get hold of the traceback of the import error. That said, the traceback is currently not printed out-of-the-box anyway, so there will not be much difference from a developer perspective... …
=> CLI: make loading of subparses more bullet-proof

cantools/database/can/formats/arxml.py, tests/test_database.py
For the message.decode() method to work properly, the key of the choices dictionary must be the raw signal's integer value mapped to the corresponding text, not vice-versa.
=> ARXML: load the choices dictionary of texttables correctly

cantools/__init__.py
The changes in this commit https://github.com/eerimoq/cantools/commit/5a9c65d9e45de36cb6c9007767cc381deac02bb6, prevented the console script working for me:
`Command "decode" is unavailable: "No module named 'cantools.__init__.subparsers'; 'cantools.__init__' is not a package"`
If calls from the script name (__init__) rather than directory. One can fix it by adding another '.': '..subparsers' but this seems messy. Since it's only going to be called from the package, it seems to make sense to just put 'cantools' in the the package field rather than using the caller name?
Now both `cantools {subparser}` and `python -m cantools {subparser}` work again.
=> Fix cli usage

.github/workflows/pythonpackage.yml, Makefile
the assumption is of this PR that these errors are caused because github-CI recently removed gcc-8 and -- maybe -- clang-8.
While I see the point of using older compilers to ensure that they stay supported, the code to be compiled is based on the C99 standard which ought to be very seasoned for at least a decade, i.e., I would be *very* surprised if compilers introduced major incompatibilities with this code in the future. IOW, let's just use the default versions of the host system...
Signed-off-by: Andreas Lauser <andreas.lauser@mbition.io>
Signed-off-by: Oliver Kopp <oliver.kopp@mbition.io>
=> attempt to fix the recently appearing test failures of PRs

cantools/logreader.py, tests/test_logreader.py
I found myself working on a CAN system that sends bits of ASCII every now and then, so it was helpful to use the `candump -a` switch.
This PR adds a few parsers compatible with the default (non-timestamped) and timestamped (-t a / -t z / -t A) outputs when using the -a switch. By compatible, I mean they don't do anything with it (since you can just look at it yourself in the data array), but they parse the rest of the line correctly.
That way, cantools decode can be used in conjunction with candump -a
=> Make parsers work with candump -a switch

cantools/__init__.py
The problem here was that the error subparser did not ignore the additional parameters intended to be passed to the actual subparser. This lead to *very* confusing error messages if additional parameters were passed to a subparser that could not be loaded.
Andreas Lauser <andreas.lauser@mbition.io> on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md#mbition-gmbh)
=> CLI: fix output in case of error

cantools/database/can/c_source.py, cantools/database/can/formats/arxml.py, cantools/database/can/formats/dbc.py, cantools/database/can/formats/kcd.py, cantools/database/can/formats/sym.py, cantools/database/can/message.py, cantools/database/can/signal.py, cantools/subparsers/utils.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py
Some file formats (err, ARXML) support this, and I occasionally consider these additional explanations to be useful.
This patch works by introducing a new class called `NamedSignalValue` and the signal choices dictionaries map to objects of it instead of raw strings. In most respects `NamedSignalValue` objects behave just like strings, but in addition they exhibit a `.comments` attribute which maps a language name to the comment für this language (just like the comments for `Signal` and `Message` objects).
Andreas Lauser <andreas.lauser@mbition.io> on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md#mbition-gmbh)
=> implement comments for named signal values

README.rst, cantools/__init__.py, cantools/subparsers/list.py, tests/test_list.py
in principle, this subparser does the same as 'dump', but it does not use ASCII art, so it is much easier to extend and the result can be grep'ed much more easily by shell scripts.
Andreas Lauser <andreas.lauser@mbition.io> on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md#mbition-gmbh)
=> add 'list' subparser

cantools/database/utils.py
is_int is only needed when scaling is True, otherwise it is defined and never used.
Also I deleted the `x is` which I believe to be a bug, because the function does not give the correct output for an int e.g 2.
I'm not sure whether `if scaling` should `elif scaling`
=> Define is_int only when it is needed

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/files/arxml/system-illegal-namespace-4.2.arxml, tests/files/arxml/system-illegal-root-4.2.arxml, tests/test_database.py
For some reason, all AR 4 revisions always use "http://autosar.org/schema/r4.0" as their XML namespace. To find out the exact AUTOSAR revision (i.e., 4.0, 4.1, 4.2, ...), the "xsi:schemaLocation" attribute of the root tag needs to be examined. Since this is pretty fragile (the used naming scheme has changed during the AR4 journey and with the latest naming scheme there seems to be no programmatic way to associate the value of schemaLocation with the AR revision), we pretend to always use AR 4.0. If incompatible changes between AR4 revisions are encountered in the future, it can be supported by implementing all posibilities and backtracking if necessary.
[Provider …
=> ARXML: always pretend to be version 4.0 for AR4

cantools/database/can/database.py, cantools/database/can/formats/arxml.py, cantools/database/can/internal_database.py, cantools/database/can/message.py, tests/test_database.py
this is completely analogous to the handling of dbc specifics. These objects currently only contain a list of the ARXML paths of all PDUs which are featured in a given message, but this will be extended in the future.
=>  Add objects for representing autosar specifics

cantools/database/can/bus.py, cantools/database/can/formats/arxml.py, cantools/database/can/message.py, cantools/database/can/signal.py, cantools/subparsers/list.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py, tests/test_list.py
This internalizes the information about the CAN buses which can be provided by ARXML files. most of the infrastructure was already present, the exception is the FD baudrate which was not around, supposedly because the base DBC file format (probably) does not support CAN-FD.
Besides this, I added the file format version of the input file to the autosar specifics of the database and cleaned up the message loading code slightly (to avoid using nested functions).
=> ARXML: extract bus information

cantools/database/__init__.py, cantools/database/can/formats/arxml.py, cantools/database/utils.py, cantools/subparsers/convert.py, cantools/subparsers/decode.py, cantools/subparsers/dump/__init__.py, cantools/subparsers/generate_c_source.py, cantools/subparsers/list.py, cantools/subparsers/monitor.py, cantools/subparsers/plot.py, tests/test_command_line.py, tests/test_database.py, tests/test_list.py, tests/test_monitor.py
This gets rid if redundant prefixes of the named values of signals thus reducing visual noise when decoding such signals considerably while still guaranteeing the uniqueness and validity of the new names.
On one hand, this requires minor modifications for some of the user scripts (sorry in advance to all affected users), but on the other hand, I think that it improves usability considerably enough to enable it by default.
=> Prune signal choices

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/files/arxml/system-float-values.arxml, tests/test_database.py
Besides accepting fractional values for floating point signals, we now also accept floating point values whenever we expect integers provided that the specified value exhibits a decimal value of `.0`. This is a superset of the AUTOSAR mandated behavior, i.e. all valid ARXML files can be loaded correctly but not all files that can be loaded are valid. (We already do this in some places so we do not really get less standard-adherent...)
This hopefully fixes [#375](https://github.com/cantools/cantools/issues/375). thanks to [at]linpanusst for bringing up this issue and for providing a publishable ARXML file to reproduce it!
[Provider …
=> ARXML: be more lenient about accepting floating point values

cantools/database/can/formats/dbc.py, tests/files/dbc/BU_BO_REL_.dbc, tests/test_database.py
This fixed some issues we had when parsing DBC files generated with CANdb++.
This is also mentioned here: https://github.com/cantools/cantools/issues/22#issuecomment-737739571
=> Add support for BU_BO_REL_ in dbc files

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py
for now, only the payload PDU is considered, i.e. the rest of the SecOC stuff is currently completely ignored. This basically means that such frames can be decoded, but encoding them in a way that "real" ECUs accept them is not yet possible.
[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
=> ARXML: implement support for secured I-PDUs

cantools/tester.py, tests/test_tester.py
also, specify the minimum required python-can version. this was motivated by https://github.com/cantools/cantools/pull/399#issuecomment-1046026905 but is probably unrelated to #399.
=> fix the tester test for newer python can versions

cantools/database/can/formats/arxml.py, tests/test_list.py
Conceptually, values that represent quantities from the physical world are always floating point values. In practice, this should not matter too much because such tables often exhibit a scaling factor of 1 and an offset of 0. It does not hurt to also handle the corner cases, though...
[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
=> ARXML: Use floats to represent the minimum and maximum of data types featuring linear segments

cantools/subparsers/dump/__init__.py, cantools/subparsers/monitor.py, tests/test_command_line.py, tests/test_monitor.py
With this PR, the `dump` subparser gains support for container messages, and `monitor` becomes useful for scenarios involving containers. The general idea is the same: For the container messages themselves, only a "table of contents" is printed, while the actual child messages are printed as separate messages named `{container.name} :: {child.name}`.
Besides this, the `monitor` subparser now only increases the number of lines used to display a given message, i.e., the "display real estate" used for a message never gets smaller. This significantly reduces the jittering of the screen contents if messages that require a variable number of lines -- like containers and multiplexer messages -- are involved. (IMO, the `monitor` subparser only has a very limited amount of value with the current …
=> monitor, dump: Improve/implement handling of container messages

cantools/database/can/message.py, tests/test_convert.py, tests/test_database.py
Passing `strict=True` to `message.encode()` is now just a shortcut for calling `message.assert_{signals,container}_encodable()` before `message.encode()`. Thus, if `strict=False` is passed, the calling code can decide which checks (if any) to apply.
Besides this, `Message.gather_signals()` is added. Given a dictionary containing a superset of all required signals, this method produces a dictionary with only the signal values that are required to encode the message. (The `Message.gather_container()` method serves the same purpose for container messages.) This is quite useful if the application's state is kept in a global dictionary, but one wants to use strict mode when encoding messages during development to avoid mistakes.
This should close …
=> Modularize the 'strict' mode for encoding messages

cantools/database/can/formats/dbc.py, tests/files/dbc/attribute_Event.dbc, tests/test_database.py
BUG fixing: 
---------------------
Prevents ValueError in case of  result = message_attributes['GenMsgSendType'].value is a String value.
Necessary in case of Evnet-based sending like in that dbc attribute expression:
BA_ "GenMsgSendType" BO_ 1373 "Event";
BA_ "GenMsgCycleTime" BO_ 1373 0;
in Vector CANdb++ generated dbcs.
Greetings Maurice
=> DBC: Add support for STRING type in GenMsgSendType

cantools/autosar/__init__.py, cantools/autosar/end_to_end.py, cantools/database/can/formats/arxml.py, cantools/subparsers/list.py, requirements.txt, tests/files/arxml/system-3.2.3.arxml, tests/files/arxml/system-4.2.arxml, tests/test_autosar.py, tests/test_database.py, tests/test_list.py
Currently we limit ourselves to profile 2 and profile 5. Besides implementing the actual E2E functionality, this PR implements the extraction the required data ids for PDUs from ARXML files into the autosar specifics of messages. Also it includes the associated unit tests and modifies the `list` subparser to display the properties required for E2E protection.
Andreas Lauser &lt;<andreas.lauser@mercedes-benz.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
=> Implement AUTOSAR end-to-end protection

cantools/autosar/__init__.py, cantools/autosar/secoc.py, cantools/autosar/snakeauth.py, cantools/database/can/formats/arxml.py, cantools/subparsers/list.py, tests/files/arxml/system-4.2.arxml, tests/test_autosar.py, tests/test_database.py, tests/test_list.py
The purpose of secure on-board communication (SecOC) is to ensure that only signals are accepted if they have been send by ECUs that are supposed to do so and that these signals are "fresh", i.e., that they are not a replay of a previous recording of the bus. Note that SecOC does *not* encrypt anything and that it also does nothing to prevent DOS attacks like a rouge ECU preventing somebody else from sending.
Also be aware that the AUTOSAR SecOC specification only specifies the scaffolding around verifying the authenticity and "freshness" of messages and does not specify any cryptographic primitives or how the freshness counter is determined (i.e., these are highly manufacturer specific). For this reason, this PR provides a `SnakeOilAuthenticator`, a set of "fake" primitives of highly …
=> Implement support for AUTOSAR secure on-board communication

setup.py
Type annotations were added in #378 but these are not exposed to clients of cantools:
error: Skipping analyzing "cantools": module is installed, but
missing library stubs or py.typed marker
Per [PEP 561], packages that include type annotations in the source code should include an empty file py.typed in the package (or a parent package). The [mypy docs] show an example using setuptools.
Diff from `pip install .; pip show -f cantools`:
--- a/before.txt
+++ b/after.txt
@@ -98,6 +98,7 @@ Files:
cantools\logreader.py
+  cantools\py.typed
cantools\subparsers\__init__.py
[PEP 561]: https://peps.python.org/pep-0561/
[mypy docs]: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
Fixes #421
=> Distribute & expose type annotations per PEP 561

cantools/database/can/formats/arxml.py, cantools/database/can/message.py, cantools/database/can/signal.py, cantools/database/diagnostics/data.py, cantools/database/utils.py, cantools/typechecking.py, docs/index.rst
Most of the perfomance benefits come from converting properties into normal attributes. Each property call results in a new stack frame which is quite expensive.
Benchmarks with some random message on my laptop:
`message.encode(data, strict=True, scaling=True)`: 49.19% improvement
`message.encode(data, strict=False, scaling=True)`: 22.98% improvement
`message.encode(data, strict=False, scaling=False)`: 60.74% improvement
This is the code i used for benchmarking:
```python3
import timeit
setup = """
import cantools
db = cantools.db.load_file("path_to_OEM_dbc")
message = db.get_message_by_name("OEM_message_name")
data = {signal.name: min(0x40, signal.maximum-1) for signal in message.signals}
"""
print(min(timeit.Timer('message.encode(data, strict=False, scaling=False)', …
```
=> Improve encoding performance

cantools/database/diagnostics/formats/cdd.py, tests/files/cdd/example-diddatarefs.cdd, tests/test_diagnostics_database.py
Some data objects are not directly part of the variant specific DID XML elements but are instead referencing to another location, this pr helps with that.
All diagnostics unit tests are still passing and a new test for this functionality has been added.
=> Fix parsing of referenced data in CDDs

cantools/autosar/end_to_end.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py, tests/test_list.py, tests/test_plot.py
I fixed test to pass it in master branch in large time difference zones and fix misspelling.
1.
Master branch doesn't pass make test in Japan or other large time difference zones from GMT.
This is caused by hard coding dates in test_plot.py. 
2.
There are some misspellings and codespelling outputs error.
=> Fix test_plot to pass it in large time difference zone and fix misspelling 

cantools/database/can/formats/arxml.py
Some ARXML files (which was provided by our clients) contain FRESSNESS-VALUE-LENGTH with a value of zero.  Currently cantools cannot load such arxml files:
```
File "/usr/local/lib/python3.6/site-packages/cantools-37.1.0-py3.6.egg/cantools/database/can/formats/arxml.py", line 1047, in _load_message
sort_signals=self._sort_signals)
File "/usr/local/lib/python3.6/site-packages/cantools-37.1.0-py3.6.egg/cantools/database/can/message.py", line 142, in __init__
self.refresh()
File "/usr/local/lib/python3.6/site-packages/cantools-37.1.0-py3.6.egg/cantools/database/can/message.py", line 1272, in refresh
self._check_signal_lengths()
File "/usr/local/lib/python3.6/site-packages/cantools-37.1.0-py3.6.egg/cantools/database/can/message.py", line 1260, in _check_signal_lengths
self.name)) …
```
=> fix exception when arxml contains FRESSNESS-VALUE-LENGTH with zero.

cantools/database/can/formats/sym.py, tests/files/sym/jopp-6.0.sym, tests/test_database.py
- When searching for SEND, RECEIVE, etc sections,
don't stop when we find the first one. Keep iterating
in case there are multiple
Closes #454
=> Handle Multiple Section Headers in SYM File

cantools/database/can/database.py, cantools/database/can/formats/dbc.py, cantools/database/utils.py, tests/test_database.py
In this commit I've added to `Database.as_dbc_string`:
- `sort_attribute_signals`: for sorting non-message signal definitions in comments, attributes, value tables etc
- `sort_attributes`: for sorting `BA_` entries, given a list of tuples for each attribute type (dbc/node/message/signal)
- `sort_choices`: For sorting the values inside choices. Convention in existing files seems to be by value, descending, but I've left the default to not sort
- `shorten_long_names`: To disable the long name truncation/conversion
I also added some additional sorters, and examples for the new sorters to utils.py, as well as tests.
Hopefully the style is OK and you're happy with the general architecture! `sort_attributes` required some big changes.
`sort_attribute_signals` might need a better name, …
=> Extended formatting options for DBC serialisation

cantools/database/can/formats/arxml.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py
This is the preparation PR for ripping the ARXML code apart into separate files. Since such changes are notoriously hard to review, I've decided to do a separate PR for the few functional changes required. (i.e., not using any global constants in `is_ecu_extract()` anymore.) The remaining part will not contain any functional changes.
Andreas Lauser &lt;<andreas.lauser@mercedes-benz.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
=> ARXML refactoring preparations

cantools/database/can/__init__.py
Allows users to directly create Bus objects
=> Add missing Bus import in can/__init__.py

cantools/subparsers/dump/__init__.py
it seems to cause issues when trying to redirect the output of the subparser on windows. Since it is only used to determine the width of the terminal anyway, let's determine that using `os.get_terminal_size()`.
Andreas Lauser &lt;<andreas.lauser@mercedes-benz.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
=> do no longer use the ncurses module in the dump subparser

setup.py
crccheck is actually used in the cantools package, so it should be in install_requires.
https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/
=> Add missing crccheck dependency to setup.py

cantools/database/can/formats/dbc.py, tests/files/dbc/attributes_relation.dbc, tests/test_database.py
dbc: corrected indentation error that occurred in [https://github.com/cantools/cantools/pull/477](477)
=> Bugfix in handling more than one node mapped attribute per signal

cantools/database/can/database.py, cantools/database/can/message.py, cantools/database/utils.py, cantools/typechecking.py
- Use `Mapping` instead of `Dict` where possible, see the commit message of commit 7f853c660768d6142a4c027acdeb567e827d42d0
- Return type of `Database.decode_message` is not considered to be `Any` with `mypy --strict`, see the commit message of commit 72e1642b590513001f235e20b5378d4fd29b806d
=> Typing improvements

cantools/database/can/formats/arxml/system_loader.py
Corrects a bug where floats can leak into the Signal.decimal attribute and cause operator errors elsewhere when minimums and maximums are operated on in conjunction with offsets and factors
=> Ensure that only Decimal types are stored in the Signal.decimal attribute

cantools/subparsers/plot.py
When trying to plot a NamedSignalValue, the following error occurs.
```
error: float() argument must be a string or a real number, not 'NamedSignalValue'
```
Use `__repr__()` when plotting to allow all signal types to be plotted.
=> fix: use __repr__() when adding values to plot

cantools/database/can/formats/arxml/system_loader.py, tests/files/arxml/system-4.2.arxml, tests/test_database.py, tests/test_list.py
Instead of breaking the parser if PDU is none, just return an empty message. The same result occurs if a PDU does not contain any signals.
=> Relaxed an PDU assert for ARXML format.

cantools/database/can/signal.py
mainly, we now refrain from doing fancy stuff with exceptions...
Andreas Lauser &lt;andreas.lauser@mercedes-benz.com&gt;, on behalf of [MBition GmbH](https://mbition.io/).
=> signal: slightly refactor `scaled_to_raw()` and `raw_to_scaled()`

cantools/autosar/end_to_end.py, cantools/autosar/secoc.py, cantools/autosar/snakeauth.py, cantools/database/can/database.py, cantools/database/can/formats/arxml/system_loader.py, cantools/database/can/message.py, cantools/database/can/signal.py, cantools/database/diagnostics/data.py, cantools/database/utils.py, cantools/logreader.py, cantools/subparsers/__utils__.py, cantools/typechecking.py, tests/test_database.py
this renames the `field` variables of the encoding and decoding utility functions back to `signal` and prepares them for piecewise linear functions.
Andreas Lauser &lt;andreas.lauser@mercedes-benz.com&gt;, on behalf of [MBition GmbH](https://mbition.io/).
=> rename `field` to `signal`

cantools/database/can/formats/dbc.py, tests/files/dbc/fd_test.dbc, tests/test_database.py
Properly populates the `is_fd` flag for messages loaded from dbc files. 
Also indirectly fixes the dbc file dump of previously loaded files that either contain FD frames or have values other than `StandardCAN` as a default in their frame format definition.
=> Fix CAN-FD detection for dbc files

cantools/database/can/formats/dbc.py, tests/test_database.py
I modeled this after the way GenMsgCycleTime is synchronized with Message.cycle_time.
=> dbc: dump_string: set GenSigStartValue from Signal.raw_initial

cantools/database/can/formats/sym.py, cantools/typechecking.py, tests/files/sym/test_multiplex_dump.sym, tests/test_database.py
The function `_dump_message` uses multiplexer signal id as the signal name. However, it might be incompatible in some platforms, such as the screenshot shown.
In addition, using the ID as the name of the multiplexer signal is not clear enough for people to understand the meaning of this multiplexer. For this issue, I'd suggest that if the multiplexer signal has an original name, use the signal name rather than use the signal id.
=> set name option for multiplexer signal

pyproject.toml
Closes #584 
Maybe we should switch to a `src/cantools` package structure in the future. The tests would have failed in this case.
=> Fix ImportError

cantools/database/can/formats/dbc.py, cantools/database/can/message.py, tests/files/dbc/bus_comment_bare_out.dbc, tests/files/dbc/comments_hex_and_motorola_converted_from_sym.dbc, tests/files/dbc/mod_name_len_dest.dbc
- Moves default fallback to the getter instead of the initial load from DBC
- Only creates the `GenMsgCycleTime` attribute if it's missing _and_ needed
- Doesn't serialise default values if they haven't been changed
It _feels_ like the current test suite is sufficient to validate this change, but feel free to request some more.
Closes #588, closes #540.
=> Make cycle_time serialisation more consistent for DBC files

cantools/__init__.py
When running cantools, depending on how it is launched, the help message will give different program names after the word `usage:` which can be set to a distinct name. Instead of deferring this to the default (os.path.basename(sys.argv[0])) in argparse, specify program name explicitly in argparse options.
```
$ python -m cantools --help
usage: __main__.py [-h] [-d] [--version] {decode,monitor,plot,convert,dump,generate_c_source,list} ...
Various CAN utilities.
...
```
(pip installed)
```
$ cantools --help
usage: cantools [-h] [-d] [--version]
{decode,monitor,dump,convert,generate_c_source} ...
Various CAN utilities.
...
```
```
$ python -m cantools --help
usage: cantools [-h] [-d] [--version] {decode,monitor,plot,convert,dump,generate_c_source,list} ...
Various CAN utilities.
...
```
(pip …
=> Add prog option to argparse for help messages

src/cantools/subparsers/monitor.py, tests/test_monitor.py
changed monitor.py to use curses erases instead of clear. Clear does a wholesale clear of everything on the screen where erase will only update the characters on the screen that need changing.
This addresses issue #606
=> Solved screen flicker problem

examples/dbc_io/main.py, examples/diagnostics/did.py, examples/hello_world.py, examples/motor_tester/main.py, examples/motor_tester/motor.py, pyproject.toml, src/cantools/database/can/message.py, src/cantools/database/diagnostics/did.py, src/cantools/database/utils.py, src/cantools/subparsers/__utils__.py, src/cantools/subparsers/decode.py, src/cantools/subparsers/monitor.py, src/cantools/typechecking.py, tests/test_autosar.py, tests/test_command_line.py, tests/test_conversion.py, tests/test_convert.py, tests/test_database.py, tests/test_database_utils.py, tests/test_diagnostics_database.py, tests/test_dump.py, tests/test_list.py, tests/test_logreader.py, tests/test_monitor.py, tests/test_plot.py, tests/test_plot_unittests.py, tests/test_plot_without_mock.py, tests/test_tester.py
This pull request mainly contains a few improvements for working with container frames:
- The output of the `decode` utility is now quite a bit nicer (IMO)
- When encoding container frames and specifying the binary payload of child frames directly, the data do no longer needs to exhibit to the size specified by the message description (instead of raising an exception, a log message will be produced)
- by default, decoding frames now fails if the payload to be decoded is longer than expected. To decode such data, passing `allow_excess=True` to the respective decode function is now required
- besides ignoring some inconsistencies in the database, passing `--no-strict` to `cantools decode` now tries to decode incorrectly-sized frames on a best effort basis. (if the received data was too …
=> Container improvements

src/cantools/database/can/__init__.py, src/cantools/database/can/c_source.py, tests/files/c_source/floating_point_use_float.c, tests/test_command_line.py
- add type annotations to c_source.py
- use float literals if `--use-float` is set
- do not cast `double` to `float`
Closes #604
=> Add type annotations to c_source.py

src/cantools/database/can/formats/sym.py, tests/files/sym/test_multiline_enum.sym, tests/test_database.py
Fixes issue #642 by creating a newline every 10 choice entries for generated sym files as part of the _dump_choice(signal) function
=> Enum newlines

src/cantools/database/can/formats/sym.py
I ran into issues when I had a really small scaling factor in a sym file and it had a scientific number and this update to the tokenizer fixed the issue.
=> slight modification to regex to enable small scaling factors that have scientific numbers in them

src/cantools/database/can/c_source.py, src/cantools/database/can/formats/dbc.py, src/cantools/database/can/message.py, src/cantools/database/can/signal_group.py, src/cantools/database/diagnostics/data.py, src/cantools/database/diagnostics/formats/cdd.py, src/cantools/j1939.py, src/cantools/subparsers/generate_c_source.py, src/cantools/subparsers/plot.py
This fixes all ruff linter errors and makes the Github workflow green.  Mostly auto-fixes from ruff, with manual inspection to verify sanity.
=> fix ruff linter errors

src/cantools/database/can/formats/kcd.py
Dumping a newly populated DB to KCD fails since the default value of the `version` attribute is `None` and the XML writer cannot handle it. This PR skips setting that value altogether if it is `None`, similarly to [what is done for the DBC format](https://github.com/cantools/cantools/blob/116333d1e1a01dc3afa3f03c5b646a6d512392af/src/cantools/database/can/formats/dbc.py#L458).
```python3
db = cantools.database.Database()
signal = cantools.database.Signal(name="Sig", start=0, length=8)
message = cantools.database.Message(frame_id=0x42, name="CAN_Message_Name", length=1, signals=[signal], strict=True)
db.messages.append(message)
db.refresh()
cantools.database.dump_file(db, "test.kcd")
```
```plaintext
Traceback (most recent call last):
File "/usr/lib64/python3.12/xml/etree/ElementTree.py", …
```
=> Skip dumping KCD version if unset

src/cantools/database/can/message.py, src/cantools/database/utils.py, src/cantools/subparsers/__utils__.py, src/cantools/subparsers/monitor.py, tests/test_monitor.py
Decoding message with bad length (and using `--no-strict`) raises exception in decoding that is caught in `format_message` and returned as a string that causes uncaught exception when `--single-line` is not used:
```shell-session
$ ip link add dev vcan0 type vcan
$ ip link set up vcan0
$ cantools -d monitor -c vcan0 tests/files/dbc/bad_message_length.dbc --no-strict
File "monitor.py", line 540, in update
modified = self.update_messages()
File "monitor.py", line 531, in update_messages
self.try_update_message()
File "monitor.py",line 417, in try_update_message
formatted = [f'{timestamp:12.3f}  {lines[1]}']
IndexError: list index out of range
$ cansend vcan0 001#11
```
This patch handles all decoding exceptions directly in monitor in a single place.
=> monitor: fix crash while decoding message with bad length

.github/workflows/pythonpackage.yml, src/cantools/database/__init__.py, tox.ini
Enable database cache via environment variable `CANTOOLS_CACHE_DIR` so tools like `monitor`, `dump` or any other user scripts can start faster without any source code modification:
```shell-session
$ export CANTOOLS_CACHE_DIR=/tmp
$ cantools dump somebig.arxml
```
Cache key is extended with all `load` arguments like `prune_choices` or `frame_id_mask` as they influence the resulting database. Few unit tests were failing because different database load configurations had same cache key.
Database raw file content is removed from the key and replaced with file path and last modification time. Otherwise cache grows quickly in hundreds of megabytes.
=> Enable cache via env variable and improve cache key

src/cantools/database/can/formats/arxml/utils.py, tests/files/arxml/system-4.2.arxml
My local arxml dealer got me some stuff with scientific notations and hexadecimal numbers in it. I am not sure if that is pure, but it works with some small tweaks to the parse_number_string function.
=> ARXML parsing: scientific and hexadecimal numbers

src/cantools/database/can/formats/arxml/utils.py, src/cantools/subparsers/plot.py
Currently, the arxml `parse_number_string` utils function parses numeric values as a `float` first, and converts to integer if an integer is required. For very large integers, floating-point error causes the integer to be parsed incorrectly.
```
>>> int(2**64 -1)
18446744073709551615
>>> int(float(2**64 -1))
18446744073709551616
```
This pull request orders the parsing attempts to prevent using `float` at all for parsing integer strings when possible.
=> fix floating-point precision issue in arxml 'parse_number_string'

src/cantools/database/utils.py
Some signal definitions may have multiple 'named signal values' with the same name but different raw numeric values (things like "reserved"). Currently, when the `encode()` function is called with signal values of type `NamedSignalValue`, the `.name` attribute is used to look up the appropriate raw numeric value. In the case of multiple 'named signal values' with the same name, this may not be encoding what the caller wants.
This PR changes the `encode()` behavior to encode the NamedSignalValue `.value` attribute, while still checking that the given name/value pair exists in the signal definition.
=> Encode the given NamedSignalValue 'value' when explicitly given

src/cantools/subparsers/plot.py, tests/test_plot.py
This pull request adds a command line option to show the unit of each signal in the legend.
Excerpt from the help (The last line is new):
```
The following options can be used to configure the subplots/axes.
If they shall apply to a specific subplot/axis they must be placed among the signals for that subplot/axis and a -- must mark the end of the global optional arguments.
Otherwise they are used as default value for each subplot/axis.
--title TITLE
--color COLOR         The color to be used for the y-label and the signals
(unless a different color is given for the signal).
All string formats explained in the following link are
allowed:
https://matplotlib.org/tutorials/colors/colors.html
(default: None)
--xlabel XLABEL
--ylabel YLABEL
--ymin YMIN
--ymax YMAX
-u, --show-units      Add …
```
=> Add option for displaying unit from dbc in the plot legend

src/cantools/database/diagnostics/formats/cdd.py
This allows a CDD with types not explicitly specified to be loaded in the intermediate list of data types. Only data types used/referenced by DIDs are actually included in the internal database.
=> Update CDD parser to load all possible data types

src/cantools/tester.py, tests/files/dbc/issue_725.dbc, tests/test_tester.py
add a strict parameter for Tester and Message, so that user can have control whether raise EncodeError for #725
=> add a strict par to fix #725

README.rst, examples/motor_tester/motor.py, src/cantools/database/can/database.py, src/cantools/subparsers/monitor.py, src/cantools/tester.py, tests/test_database.py, tests/test_monitor.py, tests/test_tester.py
If an extended frame was having an ID that would be <= 0x7FF, then it would collide with the ID of a standard frame
This is fixed by setting the top bit i.e. OR'ing the frame by 0x80000000 similar to what is done in DBC files and in the Linux kernel
Fixes #654
=> Fix frame collisions between extended and standard frames

pyproject.toml, src/cantools/__init__.py, src/cantools/autosar/__init__.py, src/cantools/database/__init__.py, src/cantools/database/can/__init__.py, src/cantools/database/can/formats/arxml/__init__.py, src/cantools/database/diagnostics/__init__.py, tests/test_autosar.py, tests/test_convert.py, tests/test_database.py, tests/test_diagnostics_database.py, tests/test_dump.py, tests/test_plot.py, tests/test_tester.py
I removed the star imports and added missing imports where tests required it.
I decided against removing `cantools.db` completely, after seeing how often it was used in our own tests.
Instead, a DeprecationWarning was added to warn against use of `cantools.db`
=> Add cantools.db DeprecationWarning

src/cantools/database/can/bus.py
`bus.py` was previously untyped, so this PR adds basic typing.
=> Add typing to bus.py
