cantools/cantools

- cantools/db/formats/dbc.py
- tests/test_cantools.py
just the grammar, so file parsing with these keywords gets possible.
data is not further processed at all
for additional information, sample lines and explanation, please visit: #12
> added Grammar for relative attributes

- cantools/db/formats/dbc.py
- tests/files/test_extended_id_dump.dbc
- tests/files/test_multiplex_dump.dbc
- tests/test_database.py
I know that you do not consider the as_ functions as API, but have them working is helpful to me. Thank you for your work here.
Update: Fixed double space for non muxed signal dumps.
> Added missing information to dbc dump.

- cantools/db/formats/kcd.py
- tests/test_database.py
I needed a support for multiplexing for KCD file format, this PR adds just that.
> Add support for loading multiplexers in KCD format

- cantools/subparsers/monitor.py
I found that the `--single-line` option under the decode subparser rather useful when looking at many messages, and was missing it when using the `monitor` subparser.
This implements support for the `--single-line` argument for the sake of consistency with the `decode` subparser.
> Add support for --single-line in monitor subparser

- cantools/database/can/formats/dbc.py
- tests/files/dbc/attributes.dbc
- tests/files/dbc/floating_point.dbc
- tests/files/dbc/motohawk.dbc
- tests/files/dbc/timing.dbc
- tests/files/dbc/val_table.dbc
- tests/files/dbc/vehicle.dbc
- tests/test_database.py
- Added support for multiple message senders when dumping DBC
- Added escaping of double quotes in comments when dumping
> Dumping to DBC compatible with Vector

- MANIFEST.in
- cantools/database/__init__.py
- tests/files/dbc/issue_168.DBC
- tests/test_database.py
Closes #165 --> accept database file extension both upper case/lower case/any combination
> File ext ignore case

- cantools/compat.py
- cantools/database/__init__.py
- tests/files/dbc/issue_163_newline.dbc
- tests/test_database.py
> Enforce windows newline for dbc

- cantools/subparsers/decode.py
- tests/test_command_line.py
Hello,
This adds support for decoding of candump log format in the CLI.
Cheers,
Axel
> Decoding of candump log format

- cantools/subparsers/plot.py
> lack of matplolib does not error until actually running subcommand

- tests/test_command_line.py
Running the tests locally with curses installed failed if terminal
wasn't 80 columns wide. Since the tests expect line breaks at 80,
we make sure that curses return that expected width.
> Mock screen width in decode tests

- cantools/tester.py
Bugfix for issue described here: https://github.com/eerimoq/cantools/issues/251
> Initial value calculation according to Vector CANdb++

- cantools/database/can/formats/arxml.py
- tests/files/arxml/system-4.2.arxml
This improves handling of references in ARXML insofar that arbitrary objects may now be referenced (instead of just elements of packages) and that the somewhat reasonable use cases for relative references are now supported.
> ARXML: improve reference handling

- cantools/subparsers/list.py
- tests/test_list.py
this is analogous to the `dump` subparser.
> list subparser: introduce a non-strict mode

- cantools/database/can/message.py
- tests/test_database.py
this should fix issue [373](https://github.com/cantools/cantools/issues/373)
> fix issue #373

- .github/workflows/pythonpackage.yml
- cantools/database/__init__.py
- cantools/database/can/database.py
- cantools/database/can/formats/dbc.py
- cantools/database/can/formats/kcd.py
- cantools/database/can/message.py
- cantools/database/can/node.py
- cantools/database/can/signal.py
- cantools/database/utils.py
- cantools/subparsers/monitor.py
- cantools/tester.py
- cantools/typechecking.py
- pyproject.toml
- requirements.txt
Add some type annotations to improve code completion in IDEs
> Add type annotations to Database, Message and Signal

- cantools/database/can/formats/sym.py
- tests/files/sym/jopp-6.0.sym
- tests/test_database.py
Closes #413
Add logic to parse the SPN from sym files and add them to signals
> Parse SPNs in SYM Files

- cantools/database/__init__.py
- cantools/database/can/database.py
- cantools/database/can/formats/sym.py
- tests/files/sym/test_extended_id_dump.sym
- tests/files/sym/test_multiplex_dump.sym
- tests/test_database.py
* Logic to convert cantools database to sym file
* Basic unit tests written - may be limitations converting from specific formats to SYM, but general functionality is implemented
> Add Support for Dumping Database as SYM File

- cantools/database/can/formats/sym.py
- Fix newline issue with multiplexed messages
- Put quotes around all units (in case of space
in units)
- Bugs introduced in #431 and noticed during internal testing
> Fix SYM file bugs

- cantools/database/can/formats/utils.py
- cantools/database/utils.py
- pyproject.toml
- tests/test_database.py
> Use floating point scaling in encoding

- cantools/database/can/formats/dbc.py
- tests/files/dbc/BU_BO_REL_.dbc
- tests/files/dbc/attributes_relation.dbc
- tests/test_database.py
dbc: updated load & dump to handle REL attributes
Added dbc file with rel attributes
test_database: added function to test new feature
> Added code to handle Node Mapped attributes

- cantools/database/__init__.py
> Change other prune_choices defaults to False

- tests/test_database.py
> Fix 'Assertation' NameError typo in test_database

- cantools/autosar/end_to_end.py
- cantools/database/utils.py
- tests/test_autosar.py
> A few bug fixes

- cantools/autosar/secoc.py
- cantools/autosar/snakeauth.py
- cantools/database/can/node.py
- cantools/database/can/signal.py
- cantools/database/diagnostics/data.py
- cantools/database/utils.py
- cantools/subparsers/__utils__.py
- cantools/typechecking.py
library file is better to import from a relative path.
> cantools library import lib from a relative path (unified)

- .github/workflows/pythonpackage.yml
- .readthedocs.yml
- README.rst
- cantools/database/__init__.py
- cantools/database/can/formats/arxml/end_to_end_properties.py
- cantools/database/can/formats/arxml/message_specifics.py
- cantools/database/can/message.py
- docs/conf.py
- docs/requirements.txt
- pyproject.toml
- tests/test_plot.py
- tests/test_plot_without_mock.py
- tox.ini
Python 3.11 just needed a version update of coverage.py and pytest-cov. There is a failing test though.
I also added a .readthedocs.yml file to address #487
> Test on python 3.11, build docs again

- README.rst
trying to fix [this issue](https://github.com/cantools/cantools/issues/487#issuecomment-137139501)
> Changed relative links to absolute links

- cantools/tester.py
> Allow cantools.tester to work with multiplexed signals

- setup.py
> Update bitstruct to >=8.16.1

- cantools/database/can/formats/sym.py
- cantools/database/can/signal.py
Related to the discussion in #515
> Make scale and offset attribute of Decimal mandatory

- cantools/database/can/formats/arxml/system_loader.py
- cantools/database/can/formats/dbc.py
- cantools/database/can/formats/kcd.py
- cantools/database/can/formats/sym.py
- cantools/database/can/message.py
- cantools/database/can/signal.py
- cantools/database/namedsignalvalue.py
- cantools/database/utils.py
- cantools/subparsers/__utils__.py
- cantools/subparsers/list.py
- cantools/subparsers/plot.py
- cantools/typechecking.py
- tests/test_database.py
Andreas Lauser &lt;andreas.lauser@mercedes-benz.com&gt;, on behalf of [MBition GmbH](https://mbition.io/).
> move the NamedSignalValue class into its own file

- .github/workflows/pythonpackage.yml
- cantools/database/can/c_source.py
- cantools/database/can/formats/arxml/system_loader.py
- cantools/database/can/formats/dbc.py
- cantools/database/can/formats/kcd.py
- cantools/database/can/formats/sym.py
- cantools/database/can/message.py
- cantools/database/can/signal.py
- cantools/database/can/signal_group.py
- cantools/database/diagnostics/data.py
- cantools/database/utils.py
- cantools/j1939.py
- cantools/subparsers/__utils__.py
- cantools/subparsers/dump/formatting.py
- cantools/subparsers/plot.py
- cantools/tester.py
- pyproject.toml
- setup.py
> Activate pyflakes-bugbear and flake8-comprehensions checks

- cantools/database/can/formats/arxml/system_loader.py
- tests/files/arxml/system-4.2.arxml
> Fix arxml AttributeError with empty comments

- examples/dbc_io/main.py
- pyproject.toml
- src/cantools/database/can/formats/arxml/ecu_extract_loader.py
- src/cantools/database/can/formats/arxml/message_specifics.py
- src/cantools/database/can/formats/dbc.py
- src/cantools/database/can/message.py
- src/cantools/database/conversion.py
Closes #618 
Closes #610 (hopefully)
> Refactor dbc GenMsgCycleTime handling

- src/cantools/database/can/formats/dbc.py
- src/cantools/database/can/message.py
- src/cantools/database/utils.py
- tests/files/dbc/issue_636_negative_scaling.dbc
- tests/test_command_line.py
- tests/test_convert.py
- tests/test_database.py
- tests/test_list.py
- tests/test_monitor.py
- tests/test_plot.py
- tests/test_tester.py
- tox.ini
> Fix range check with negative scalings

- src/cantools/database/can/formats/dbc.py
- tests/test_database.py
> Fix J1939 SPN parsing

- docs/conf.py
- src/cantools/database/can/database.py
- tests/test_database.py
- tests/test_plot.py
- tests/test_plot_unittests.py
- tests/test_plot_without_mock.py
this makes the CI pass again. (at least for non-MacOS systems.)
> fix errors raised by recent versions of `ruff`

- src/cantools/database/can/formats/dbc.py
Fixes a bug where with certain constellations of long names duplicated short names are generated.
> Fix bug in DBC short names conversion

- src/cantools/database/can/formats/dbc.py
- tests/test_database.py
Continuation of #660
Closes #693
> Add test and type annotations for LongNamesConverter

- src/cantools/subparsers/monitor.py
- tests/test_monitor.py
Case insensitive filtering of frame names in monitor.
> monitor: case insensitive filtering

- src/cantools/database/can/database.py
- src/cantools/database/can/formats/kcd.py
> Modify the default version to be an empty string

- src/cantools/database/can/c_source.py
- tests/files/c_source/open_actuator_sender_node.c
- tests/files/c_source/open_actuator_sender_node.h
- tests/files/c_source/open_actuator_sender_node_no_floating_point_numbers.c
- tests/files/c_source/open_actuator_sender_node_no_floating_point_numbers.h
- tests/test_c_code/CMakeLists.txt
> Fix compiler error for code generated with --node arg
